services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment: {}
    ports:
      - "8001:8001"
    restart: no

    # Ensure host.docker.internal resolves on Linux too
    extra_hosts:
      - "host.docker.internal:host-gateway"

