"""Initial migration

Revision ID: ede674635cf9
Revises: 
Create Date: 2025-07-25 12:09:38.244098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede674635cf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('unsupervised_label', sa.Boolean(), nullable=False),
    sa.Column('supervised_label', sa.Boolean(), nullable=False),
    sa.Column('mismatch', sa.Boolean(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('expert_label', sa.String(), nullable=True),
    sa.Column('final_classification', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_records_id'), 'anomaly_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_records_id'), table_name='anomaly_records')
    op.drop_table('anomaly_records')
    # ### end Alembic commands ###
