dataset:
  name: decospan
  format: folder
  path: E:\ML - Self Study\MV4QC_back_end\app\models\unsupervised\dataset\decospan_small
  normal_dir: normal
  abnormal_dir: anomaly
  image_size: [256, 256]
  normalization: imagenet
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  val_split_mode: from_train
  val_split_ratio: 0.2
  seed: 42

model:
  name: padim
  backbone: resnet18
  layers: ["layer1", "layer2", "layer3"]

trainer:
  default_root_dir: output/padim
  enable_checkpointing: true

optimization:
  export_mode: torch